### ISSUE TITLE
Make it docker friendly

### ISSUE THREAD

**Issue by patrickdk77** [php-mongo/admin#10]
Is there any way to make this more docker friendly?
I want to deploy it for our developers into their che-ide enviroment so they can have a gui to work on to develop with their mongo instances.
But it appears this needs to know what hostname it's installed at, that is dynamically created each time it's launched, and appears to have sqlite/redis/... dependencies for some reason also.

**Comment by phpmongo** [comment]
Hello and thanks for your input.

I have planned to work on Installation methods and variants after the initial build process is complete. I estimate that will be in about 2 weeks.
My understanding of what you wish to achieve is to deploy the application in a 'local' dev environment where there would be no immediate requirement for authentication.

Have you already tried to load the app with a docker FPM CLI? Any specific reported errors may help fast track a fix.

The SQLite dependency caters for the application access requirements.
Host-names are treated dynamically, and we have modified the app so that it can be installed a child object.

The initial scope for this application was as a stand-alone DB admin tool, much like PhpMyAdmin.
One of the install options I'll be implementing will be a bash shell script install method.

Having worked with docker quite a bit in the last 6 months I  can see the value in making that work.
Feel free to offer any specific requirements or expectations on how that app would be loaded/accessed

Regards,
                   Gilbert

**Comment by gilbert-rehling** [comment]
This body of work has now beel complted to a satifactory level.
We now have 2 dedicated docker-compose repositories;
1)  Full stand alone with Apache2, MongoDB image and PhpMongoAdmin install in default global access mode (great for developing an apllication where easy acess to MongoDo admin is required)
2) Stand alone with Apache2 and PhpMongoAdmin only - this requires a separate MongoDB, perfact for connect to Atlas or other remote service.

Easy fully  automated installations available, with options to use global (Alias config) install or VirtualHost based setup.
Tested on Windows 10 and Centos 7..
